const form=document.getElementById('assistant-form');
const question=document.getElementById('question');
const conversation=document.getElementById('conversation');
const prompts=document.querySelectorAll('.prompt-row button');
const topicButtons=document.querySelectorAll('[data-topic]');

function seed(text){question.value=text;question.focus();}
function addMessage(text,type='user'){const row=document.createElement('div');row.className=`ai-message ${type}`;row.innerHTML=`<span class="mini-orb">${type==='user'?'YOU':'AI'}</span><div><small>${type==='user'?'YOU':'TWC INTELLIGENCE'}</small><p></p></div>`;row.querySelector('p').textContent=text;conversation.appendChild(row);row.scrollIntoView({behavior:'smooth',block:'nearest'});}
function localResponse(text){const q=text.toLowerCase();if(q.includes('forex'))return 'Forex is the global market for exchanging currencies. Prices move as supply, demand, interest rates, economic data and market sentiment change. If you want, I can explain spreads, leverage and risk in simple terms.';if(q.includes('risk'))return 'Risk management is about controlling how much you could lose before focusing on potential returns. Common concepts include position sizing, diversification, stop-loss planning and avoiding leverage you do not understand.';if(q.includes('get started')||q.includes('start'))return 'A safe TWC journey begins with understanding the service, completing any required verification, reviewing the applicable disclosures and speaking with the TWC team about your specific circumstances.';if(q.includes('equities')||q.includes('stocks'))return 'Equities represent ownership interests in companies. Their prices can respond to earnings, expectations, interest rates, economic conditions and investor sentiment.';if(q.includes('digital'))return 'Digital assets use blockchain-based technology. They can be highly volatile, and their risks differ from traditional assets. I can explain the technology and market structure without making a return promise.';return 'I’m TWC Intelligence. I can explain TWC services, trading concepts and platform guidance. The live OpenAI endpoint will be connected server-side before this workspace is used for production conversations.';}
prompts.forEach(b=>b.addEventListener('click',()=>seed(b.textContent)));
topicButtons.forEach(b=>b.addEventListener('click',()=>{document.querySelector('#assistant')?.scrollIntoView({behavior:'smooth'});seed(`Tell me about ${b.dataset.topic} at TWC`)}));
form.addEventListener('submit',e=>{e.preventDefault();const value=question.value.trim();if(!value)return;addMessage(value,'user');question.value='';const send=form.querySelector('button');send.disabled=true;send.textContent='Thinking…';setTimeout(()=>{addMessage(localResponse(value),'assistant');send.disabled=false;send.innerHTML='Send <span>→</span>';},350);});
